# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: gabrrodr <gabrrodr@student.42.fr>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2024/01/30 13:00:13 by gabrrodr          #+#    #+#              #
#    Updated: 2024/01/30 13:06:20 by gabrrodr         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

all : megaphone

megaphone:
	c++ -Wall -Wextra -Werror -std=c++98 megaphone.cpp -o megaphone
	
clean:
	rm -rf megaphone

re:
	clean all
